import { 
    GiAmericanFootballPlayer, 
    GiBaseballBat, 
    GiBasketballBall, 
    GiBoxingGlove, 
    GiCricketBat, 
    GiGolfFlag, 
    GiRaceCar, 
    GiSailboat,  
    GiTennisRacket, 
    GiVolleyballBall, 
    GiDogHouse, 
    GiHorseHead, 
    GiRugbyConversion, 
    GiEightBall,
    GiTvRemote,
    GiDart,
    GiBombingRun,
    GiBoxingRing
} from 'react-icons/gi';
import { FaBicycle, FaGamepad, FaHandHoldingUsd, FaHockeyPuck, FaMicrophoneAlt, FaTableTennis, FaTv } from 'react-icons/fa';
import { SiCounterstrike, SiRiotgames } from 'react-icons/si';
import { MdSportsHandball, MdSportsRugby } from 'react-icons/md';
import { PiSoccerBallFill } from 'react-icons/pi';
import { TbSoccerField } from 'react-icons/tb';
import { Categories, Links } from './definitions';

export const links: Links = [
    { name: "American Football", href: "/american-football", icon: <GiAmericanFootballPlayer size={20}/> },
    { name: "Baseball", href: "/baseball", icon: <GiBaseballBat size={20}/> },
    { name: "Basketball", href: "/basketball", icon: <GiBasketballBall size={20}/> },
    { name: "Boxing", href: "/boxing", icon: <GiBoxingGlove size={20}/> },
    { name: "Call of Duty", href: "/call-of-duty", icon: <GiBombingRun size={20}/> },
    { name: "Cricket", href: "/cricket", icon: <GiCricketBat size={20}/> },
    { name: "CSGO", href: "/csgo", icon: <SiCounterstrike size={20}/> },
    { name: "Current Affairs", href: "/current-affairs", icon: <FaMicrophoneAlt size={20}/> },
    { name: "Cycling", href: "/cycling", icon: <FaBicycle size={20}/> },
    { name: "Darts", href: "/darts", icon: <GiDart size={20}/> },
    { name: "Dota 2", href: "/dota-2", icon: <FaGamepad size={20}/> },
    { name: "Football Esports", href: "/football-esports", icon: <TbSoccerField size={20}/> },
    { name: "Football", href: "/football", icon: <PiSoccerBallFill size={20}/> },
    { name: "Golf", href: "/golf", icon: <GiGolfFlag size={20}/> },
    { name: "Greyhound Racing", href: "/greyhound-racing", icon: <GiDogHouse size={20}/> },
    { name: "Handball", href: "/handball", icon: <MdSportsHandball size={20}/> },
    { name: "Horse Racing", href: "/horse-racing", icon: <GiHorseHead size={20}/> },
    { name: "Ice Hockey", href: "/ice-hockey", icon: <FaHockeyPuck size={20}/> },
    { name: "League of Legends", href: "/league-of-legends", icon: <SiRiotgames size={20}/> },
    { name: "MMA", href: "/mma", icon: <GiBoxingRing size={20}/> },
    { name: "Motorsports", href: "/motorsports", icon: <GiRaceCar size={20}/> },
    { name: "Politics", href: "/politics", icon: <FaHandHoldingUsd size={20}/> },
    { name: "Rowing", href: "/rowing", icon: <GiSailboat size={20}/> },
    { name: "Rugby League", href: "/rugby-league", icon: <GiRugbyConversion size={20}/> },
    { name: "Rugby Union", href: "/rugby-union", icon: <MdSportsRugby size={20}/> },
    { name: "Sailing", href: "/sailing", icon: <GiSailboat size={20}/> },
    { name: "Snooker", href: "/snooker", icon: <GiEightBall size={20}/> },
    { name: "Table Tennis", href: "/table-tennis", icon: <FaTableTennis size={20}/> },
    { name: "Tennis", href: "/tennis", icon: <GiTennisRacket size={20}/> },
    { name: "Volleyball", href: "/volleyball", icon: <GiVolleyballBall size={20}/> },
    { name: "Top Level Event", href: "/top-level-event", icon: <GiTvRemote size={20}/> },
    { name: "TV Entertainment", href: "/tv-entertainment", icon: <FaTv size={20}/> }
];

export const categories: Categories = {
    "american-football": { name: "American Football", types: ["american_football_match", "american_football_outright"] },
    "baseball": { name: "Baseball", types: ["baseball_match", "baseball_outright"] },
    "basketball": { name: "Basketball", types: ["basketball_esports_match", "basketball_match"] },
    "boxing": { name: "Boxing", types: ["boxing_match"] },
    "call-of-duty": { name: "Call of Duty", types: ["call_of_duty_match"] },
    "cricket": { name: "Cricket", types: ["cricket_match", "cricket_outright"] },
    "csgo": { name: "CSGO", types: ["csgo_match"] },
    "current-affairs": { name: "Current Affairs", types: ["current_affairs"] },
    "cycling": { name: "Cycling", types: ["cycling"] },
    "darts": { name: "Darts", types: ["darts_match", "darts_outright"] },
    "dota-2": { name: "Dota 2", types: ["dota_2_match"] },
    "football-esports": { name: "Football Esports", types: ["football_esports_match"] },
    "football": { name: "Football", types: ["football_match", "football_outright"] },
    "golf": { name: "Golf", types: ["golf_match", "golf_outright"] },
    "greyhound-racing": { name: "Greyhound Racing", types: ["greyhound_racing_race"] },
    "handball": { name: "Handball", types: ["handball_match"] },
    "horse-racing": { name: "Horse Racing", types: ["horse_racing_race"] },
    "ice-hockey": { name: "Ice Hockey", types: ["ice_hockey_match"] },
    "league-of-legends": { name: "League of Legends", types: ["league_of_legends_match"] },
    "mma": { name: "MMA", types: ["mma_match"] },
    "motorsports": { name: "Motorsports", types: ["motorsports_race", "motorsports_outright"] },
    "politics": { name: "Politics", types: ["politics", "politics_outright"] },
    "rowing": { name: "Rowing", types: ["rowing"] },
    "rugby-league": { name: "Rugby League", types: ["rugby_league_match", "rugby_league_outright"] },
    "rugby-union": { name: "Rugby Union", types: ["rugby_union_match", "rugby_union_outright"] },
    "sailing": { name: "Sailing", types: ["sailing_race", "sailing_outright"] },
    "snooker": { name: "Snooker", types: ["snooker_match", "snooker_outright"] },
    "table-tennis": { name: "Table Tennis", types: ["table_tennis_match", "table_tennis_outright"] },
    "tennis": { name: "Tennis", types: ["tennis_match", "tennis_outright"] },
    "volleyball": { name: "Volleyball", types: ["volleyball_match"] },
    "top-level-event": { name: "Top Level Event", types: ["top_level_event"] },
    "tv-entertainment": { name: "TV Entertainment", types: ["tv_entertainment"] }
};
